'use client';

import { useEffect, useState } from 'react';
import NextLink from 'next/link';
import { Alert, Box, Button, Checkbox, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, IconButton, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import AddRoundedIcon from '@mui/icons-material/AddRounded';
import ContentCopyRoundedIcon from '@mui/icons-material/ContentCopyRounded';
import DeleteOutlineRoundedIcon from '@mui/icons-material/DeleteOutlineRounded';
import PageBody from '@/lib/ui/app/PageBody';
import apiClient from '@/lib/api/client';

const blankField=()=>({fieldUuid:crypto.randomUUID?.()||String(Date.now()+Math.random()),label:'',name:'',type:'text',required:false,options:[]});
export default function InstituteFormsPage(){
 const[forms,setForms]=useState([]),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[error,setError]=useState('');
 const[form,setForm]=useState({title:'',description:'',slug:'',successMessage:'Thank you! Your response has been recorded.',createLead:true,isActive:true,fields:[blankField()]});
 const load=async()=>{try{const r=await apiClient.get('/api/institute/forms');setForms(r.data?.data||[]);}catch(e){setError(e?.response?.data?.message||'Could not load forms.')}};
 useEffect(()=>{load()},[]);
 const start=()=>{setEditing(null);setForm({title:'',description:'',slug:'',successMessage:'Thank you! Your response has been recorded.',createLead:true,isActive:true,fields:[blankField()]});setOpen(true)};
 const edit=(row)=>{setEditing(row);setForm({...row});setOpen(true)};
 const field=(i,patch)=>setForm(f=>({...f,fields:f.fields.map((x,n)=>n===i?{...x,...patch}:x)}));
 const save=async()=>{try{if(editing)await apiClient.patch(`/api/institute/forms/${editing._id}`,form);else await apiClient.post('/api/institute/forms',form);setOpen(false);await load()}catch(e){setError(e?.response?.data?.message||'Could not save form.')}};
 return <PageBody title="Public Forms" description="Create enquiry/admission forms and turn public submissions into shared CRM leads."><Stack spacing={2}>
  {error&&<Alert severity="error" onClose={()=>setError('')}>{error}</Alert>}
  <Stack direction="row" spacing={1} justifyContent="space-between"><Button component={NextLink} href="/services/institute">Institute</Button><Button variant="contained" startIcon={<AddRoundedIcon/>} onClick={start}>New form</Button></Stack>
  <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(2,1fr)'},gap:2}}>{forms.map(row=><Paper key={row._id} variant="outlined" sx={{p:2,borderRadius:3}}><Stack spacing={1}><Stack direction="row" justifyContent="space-between"><Box><Typography fontWeight={850}>{row.title}</Typography><Typography variant="body2" color="text.secondary">{row.responseCount||0} responses · {row.isActive?'Active':'Inactive'}</Typography></Box><Button size="small" onClick={()=>edit(row)}>Edit</Button></Stack><Typography variant="body2" noWrap>{row.publicUrl}</Typography><Stack direction="row" spacing={1}><Button size="small" startIcon={<ContentCopyRoundedIcon/>} onClick={()=>navigator.clipboard?.writeText(row.publicUrl)}>Copy link</Button><Button size="small" component={NextLink} href={`/forms/${row.slug}`} target="_blank">Open</Button><Button size="small" component={NextLink} href={`/services/institute/form-responses?form=${row._id}`}>Responses</Button></Stack></Stack></Paper>)}</Box>
 </Stack>
 <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="md"><DialogTitle>{editing?'Edit public form':'New public form'}</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><TextField label="Title" value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))}/><TextField label="Description" value={form.description||''} onChange={e=>setForm(f=>({...f,description:e.target.value}))}/><TextField label="Public slug" placeholder="admission-enquiry" value={form.slug||''} onChange={e=>setForm(f=>({...f,slug:e.target.value}))}/><Stack direction="row" spacing={2}><FormControlLabel control={<Checkbox checked={form.createLead!==false} onChange={e=>setForm(f=>({...f,createLead:e.target.checked}))}/>} label="Create CRM lead on submit"/><FormControlLabel control={<Checkbox checked={form.isActive!==false} onChange={e=>setForm(f=>({...f,isActive:e.target.checked}))}/>} label="Active"/></Stack><Typography fontWeight={800}>Fields</Typography>{(form.fields||[]).map((x,i)=><Paper key={x.fieldUuid||i} variant="outlined" sx={{p:1.5}}><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'2fr 1.2fr 1fr auto'},gap:1}}><TextField size="small" label="Label" value={x.label||''} onChange={e=>field(i,{label:e.target.value})}/><TextField size="small" label="Field name" value={x.name||''} onChange={e=>field(i,{name:e.target.value})}/><TextField select size="small" label="Type" value={x.type||'text'} onChange={e=>field(i,{type:e.target.value})}>{['text','email','phone','number','textarea','dropdown','radio','checkbox','date'].map(t=><MenuItem key={t} value={t}>{t}</MenuItem>)}</TextField><IconButton onClick={()=>setForm(f=>({...f,fields:f.fields.filter((_,n)=>n!==i)}))}><DeleteOutlineRoundedIcon/></IconButton></Box><Stack direction="row" spacing={2} alignItems="center" sx={{mt:1}}><FormControlLabel control={<Checkbox checked={Boolean(x.required)} onChange={e=>field(i,{required:e.target.checked})}/>} label="Required"/>{['dropdown','radio','checkbox'].includes(x.type)&&<TextField size="small" fullWidth label="Options (comma separated)" value={(x.options||[]).join(', ')} onChange={e=>field(i,{options:e.target.value.split(',').map(v=>v.trim()).filter(Boolean)})}/>}</Stack></Paper>)}<Button onClick={()=>setForm(f=>({...f,fields:[...(f.fields||[]),blankField()]}))}>Add field</Button><TextField label="Success message" value={form.successMessage||''} onChange={e=>setForm(f=>({...f,successMessage:e.target.value}))}/></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" onClick={save}>Save</Button></DialogActions></Dialog>
 </PageBody>;
}
