'use client';

import { useEffect, useMemo, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Divider, MenuItem, Paper, Stack, Tab, Tabs, TextField, Typography } from '@mui/material';
import AddRoundedIcon from '@mui/icons-material/AddRounded';
import CheckCircleRoundedIcon from '@mui/icons-material/CheckCircleRounded';
import RefreshRoundedIcon from '@mui/icons-material/RefreshRounded';
import AutoAwesomeRoundedIcon from '@mui/icons-material/AutoAwesomeRounded';
import ArrowForwardRoundedIcon from '@mui/icons-material/ArrowForwardRounded';
import apiClient from '@/lib/api/client';

const CONFIG = {
  crm: { title: 'Revenue pipeline', description: 'Turn enquiries into follow-ups, quotations and confirmed orders without duplicating customer records.', kinds: ['lead', 'followup', 'quotation', 'order'], metrics: [['Open leads', 'leadsOpen'], ['Follow-ups due', 'followupsDue'], ['Open quotations', 'quotationsOpen'], ['Open orders', 'openOrders']] },
  payments: { title: 'Payments & documents', description: 'Track quotations, orders, collections, balances and expenses from the same customer history.', kinds: ['quotation', 'order', 'payment', 'expense'], metrics: [['Sales this month', 'salesMonthPaise', 'money'], ['Collected this month', 'collectedMonthPaise', 'money'], ['Outstanding', 'outstandingPaise', 'money'], ['Expenses this month', 'expensesMonthPaise', 'money']] },
  staff: { title: 'Staff & operations', description: 'Assign tasks and keep vendor responsibilities visible. Attendance is managed by the dedicated WhatsApp + biometric panel below.', kinds: ['task', 'vendor'], metrics: [['Tasks due', 'tasksDue'], ['Tasks overdue', 'tasksOverdue'], ['Active vendors', 'vendorsActive'], ['Open orders', 'openOrders']] },
  store: { title: 'Mini store & growth', description: 'Maintain products, stock movements and review requests on top of your shared customer workspace.', kinds: ['product', 'inventory', 'review_request'], metrics: [['Active products', 'productsActive'], ['Pending reviews', 'pendingReviews'], ['Open orders', 'openOrders'], ['Outstanding', 'outstandingPaise', 'money']] },
};

const LABELS = { lead: 'Leads', followup: 'Follow-ups', quotation: 'Quotations', order: 'Orders / Jobs', invoice: 'Invoices', payment: 'Payments', expense: 'Expenses', task: 'Tasks', vendor: 'Vendors', product: 'Products', inventory: 'Inventory', review_request: 'Review requests' };
const DEFAULT_STATUS = { payment: 'received', product: 'active', inventory: 'recorded', vendor: 'active', review_request: 'pending' };
const FINAL_STATUS = { lead: 'completed', followup: 'completed', quotation: 'completed', order: 'completed', payment: 'paid', expense: 'paid', task: 'completed', review_request: 'completed' };
const TERMINAL = new Set(['completed', 'paid', 'done', 'closed', 'cancelled', 'lost', 'rejected', 'active', 'recorded', 'received']);
const NEXT = { lead: 'followup', followup: 'quotation', quotation: 'order', order: 'invoice' };
const NEXT_LABEL = { followup: 'Follow-up', quotation: 'Quotation', order: 'Order', invoice: 'Invoice' };
const money = (paise) => `₹${Math.round(Number(paise || 0) / 100).toLocaleString('en-IN')}`;
const isMoneyKind = (kind) => ['quotation', 'order', 'payment', 'expense'].includes(kind);

function MetricCard({ label, value, format }) {
  return <Paper variant="outlined" sx={{ p: 2, borderRadius: 3 }}><Typography variant="caption" color="text.secondary" fontWeight={700}>{label}</Typography><Typography variant="h5" fontWeight={800} sx={{ mt: 0.5 }}>{format === 'money' ? money(value) : Number(value || 0).toLocaleString('en-IN')}</Typography></Paper>;
}

function BusinessCopilot() {
  const [question, setQuestion] = useState(''); const [result, setResult] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const ask = async (preset) => { const text = String(preset || question).trim(); if (!text) return; setBusy(true); setError(''); try { const response = await apiClient.post('/api/smb/assistant', { question: text }); setResult(response?.data?.data || null); setQuestion(''); } catch (requestError) { setError(requestError?.response?.data?.message || 'Could not read business data.'); } finally { setBusy(false); } };
  return <Card variant="outlined" sx={{ borderRadius: 3 }}><CardContent><Stack direction="row" spacing={1} alignItems="center"><AutoAwesomeRoundedIcon fontSize="small" /><Typography variant="h6" fontWeight={800}>Business Copilot</Typography><Chip size="small" label="Live workspace data" variant="outlined" /></Stack><Typography variant="body2" color="text.secondary" sx={{ my: 1.5 }}>Ask about leads, follow-ups, outstanding payments, sales, expenses, orders or overdue tasks.</Typography><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}><TextField fullWidth size="small" value={question} onChange={(e) => setQuestion(e.target.value)} placeholder="Who needs follow-up today?" onKeyDown={(e) => { if (e.key === 'Enter') ask(); }} /><Button variant="contained" onClick={() => ask()} disabled={busy || !question.trim()}>{busy ? 'Checking…' : 'Ask'}</Button></Stack><Stack direction="row" sx={{ mt: 1, flexWrap: 'wrap', gap: 0.5 }}>{['Follow-ups due', 'Outstanding payments', 'Overdue tasks', 'Sales this month'].map((preset) => <Button key={preset} size="small" onClick={() => ask(preset)} disabled={busy}>{preset}</Button>)}</Stack>{error ? <Alert severity="error" sx={{ mt: 1 }}>{error}</Alert> : null}{result ? <Box sx={{ mt: 1.5 }}><Alert severity="info">{result.answer}</Alert>{result.items?.slice(0, 6).map((item) => <Stack key={item._id} direction="row" justifyContent="space-between" sx={{ py: 0.75, borderBottom: '1px solid', borderColor: 'divider' }}><Typography variant="body2" noWrap>{item.title} · {item.contactId?.name || item.contactId?.phone || item.assignedTo || LABELS[item.kind]}</Typography>{item.balanceInPaise ? <Typography variant="body2" fontWeight={800}>{money(item.balanceInPaise)}</Typography> : null}</Stack>)}</Box> : null}</CardContent></Card>;
}

export default function SmallBusinessWorkspace({ service }) {
  const config = CONFIG[service]; const [tab, setTab] = useState(config?.kinds?.[0] || 'lead'); const [records, setRecords] = useState([]); const [summary, setSummary] = useState({}); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [showForm, setShowForm] = useState(false); const [form, setForm] = useState({ title: '', customerName: '', customerPhone: '', assignedTo: '', amount: '', balance: '', dueAt: '', reference: '', quantity: '', status: '' });
  const kinds = useMemo(() => config?.kinds || [], [config]);
  const load = async (kind = tab) => { setLoading(true); setError(''); try { const [recordsResponse, summaryResponse] = await Promise.all([apiClient.get('/api/smb/records', { params: { kind, limit: 150 } }), apiClient.get('/api/smb/summary')]); setRecords(recordsResponse?.data?.data || []); setSummary(summaryResponse?.data?.data || {}); } catch (requestError) { setError(requestError?.response?.data?.message || 'Could not load this workspace.'); } finally { setLoading(false); } };
  useEffect(() => { load(tab); }, [tab]); // eslint-disable-line react-hooks/exhaustive-deps
  const updateForm = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value }));
  const create = async () => { if (!form.title.trim()) return; setSaving(true); setError(''); try { await apiClient.post('/api/smb/records', { kind: tab, title: form.title.trim(), customerName: form.customerName.trim(), customerPhone: form.customerPhone.trim(), assignedTo: form.assignedTo.trim(), amount: form.amount === '' ? undefined : Number(form.amount), balance: form.balance === '' ? undefined : Number(form.balance), quantity: form.quantity === '' ? undefined : Number(form.quantity), dueAt: form.dueAt || undefined, reference: form.reference.trim(), status: form.status.trim() || DEFAULT_STATUS[tab] || 'open', source: service }); setForm({ title: '', customerName: '', customerPhone: '', assignedTo: '', amount: '', balance: '', dueAt: '', reference: '', quantity: '', status: '' }); setShowForm(false); setNotice(`${LABELS[tab] || tab} record saved.`); await load(tab); } catch (requestError) { setError(requestError?.response?.data?.message || 'Could not save the record.'); } finally { setSaving(false); } };
  const finish = async (record) => { if (!FINAL_STATUS[record.kind]) return; setSaving(true); setError(''); try { await apiClient.patch(`/api/smb/records/${record._id}`, { status: FINAL_STATUS[record.kind] }); setNotice('Record updated.'); await load(tab); } catch (requestError) { setError(requestError?.response?.data?.message || 'Could not update the record.'); } finally { setSaving(false); } };
  const convert = async (record, targetKind) => { setSaving(true); setError(''); try { await apiClient.post(`/api/smb/records/${record._id}/convert`, { targetKind }); setNotice(`${LABELS[record.kind] || record.kind} converted to ${NEXT_LABEL[targetKind] || targetKind}.`); if (targetKind !== 'invoice') setTab(targetKind); await load(targetKind === 'invoice' ? tab : targetKind); } catch (requestError) { setError(requestError?.response?.data?.message || 'Could not convert the record.'); } finally { setSaving(false); } };
  if (!config) return <Alert severity="warning">This small-business workspace is not configured.</Alert>;
  return <Stack spacing={2.5}><Box><Typography variant="h6" fontWeight={800}>{config.title}</Typography><Typography variant="body2" color="text.secondary">{config.description}</Typography></Box><Box sx={{ display: 'grid', gridTemplateColumns: { xs: 'repeat(2,minmax(0,1fr))', lg: 'repeat(4,minmax(0,1fr))' }, gap: 1.25 }}>{config.metrics.map(([label, key, format]) => <MetricCard key={key} label={label} value={summary[key]} format={format} />)}</Box><BusinessCopilot />{error ? <Alert severity="error" onClose={() => setError('')}>{error}</Alert> : null}{notice ? <Alert severity="success" onClose={() => setNotice('')}>{notice}</Alert> : null}<Card variant="outlined" sx={{ borderRadius: 3 }}><Box sx={{ px: 2, pt: 1 }}><Tabs value={tab} onChange={(_e, value) => { setTab(value); setShowForm(false); }} variant="scrollable" scrollButtons="auto">{kinds.map((kind) => <Tab key={kind} value={kind} label={LABELS[kind] || kind} />)}</Tabs></Box><Divider /><CardContent><Stack direction="row" justifyContent="space-between" alignItems="center" spacing={1} sx={{ mb: 2 }}><Box><Typography variant="h6" fontWeight={800}>{LABELS[tab] || tab}</Typography><Typography variant="caption" color="text.secondary">Linked to the shared customer whenever a customer phone/contact is supplied.</Typography></Box><Stack direction="row" spacing={1}><Button size="small" startIcon={<RefreshRoundedIcon />} onClick={() => load(tab)}>Refresh</Button><Button size="small" variant="contained" startIcon={<AddRoundedIcon />} onClick={() => setShowForm((v) => !v)}>Add</Button></Stack></Stack>
  {showForm ? <Paper variant="outlined" sx={{ p: 2, borderRadius: 3, mb: 2 }}><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: 'repeat(2,minmax(0,1fr))', lg: 'repeat(3,minmax(0,1fr))' }, gap: 1.25 }}><TextField size="small" label="Title / purpose" value={form.title} onChange={updateForm('title')} required />{!['vendor','product','inventory'].includes(tab) ? <><TextField size="small" label="Customer name" value={form.customerName} onChange={updateForm('customerName')} /><TextField size="small" label="Customer phone" value={form.customerPhone} onChange={updateForm('customerPhone')} /></> : null}<TextField size="small" label={tab === 'vendor' ? 'Vendor/contact person' : 'Assigned to'} value={form.assignedTo} onChange={updateForm('assignedTo')} />{isMoneyKind(tab) ? <TextField size="small" type="number" label="Amount (₹)" value={form.amount} onChange={updateForm('amount')} /> : null}{tab === 'order' ? <TextField size="small" type="number" label="Balance due (₹)" value={form.balance} onChange={updateForm('balance')} /> : null}{['product','inventory'].includes(tab) ? <TextField size="small" type="number" label="Quantity" value={form.quantity} onChange={updateForm('quantity')} /> : null}{['followup','quotation','order','task','payment','review_request'].includes(tab) ? <TextField size="small" type="datetime-local" label="Due / action date" value={form.dueAt} onChange={updateForm('dueAt')} InputLabelProps={{ shrink: true }} /> : null}<TextField size="small" label="Reference" value={form.reference} onChange={updateForm('reference')} /><TextField size="small" select label="Status" value={form.status} onChange={updateForm('status')}><MenuItem value="">Use default</MenuItem>{['open','pending','active','received','paid','completed','cancelled'].map((status) => <MenuItem key={status} value={status}>{status}</MenuItem>)}</TextField></Box><Stack direction="row" justifyContent="flex-end" spacing={1} sx={{ mt: 2 }}><Button onClick={() => setShowForm(false)}>Cancel</Button><Button variant="contained" onClick={create} disabled={saving || !form.title.trim()}>{saving ? 'Saving…' : 'Save'}</Button></Stack></Paper> : null}
  {loading ? <Stack direction="row" spacing={1} justifyContent="center" sx={{ py: 4 }}><CircularProgress size={20} /><Typography variant="body2">Loading…</Typography></Stack> : records.length ? <Stack>{records.map((record) => { const nextKind = NEXT[record.kind]; return <Stack key={record._id} direction={{ xs: 'column', sm: 'row' }} spacing={1.5} justifyContent="space-between" alignItems={{ sm: 'center' }} sx={{ py: 1.5, borderBottom: '1px solid', borderColor: 'divider' }}><Box sx={{ minWidth: 0, flex: 1 }}><Stack direction="row" spacing={1} sx={{ flexWrap: 'wrap' }}><Typography variant="body2" fontWeight={800}>{record.title}</Typography><Chip size="small" label={record.status || 'open'} variant="outlined" /></Stack><Typography variant="caption" color="text.secondary">{[record.contactId?.name || record.contactId?.phone, record.assignedTo ? `Owner: ${record.assignedTo}` : '', record.reference ? `Ref: ${record.reference}` : '', record.dueAt ? `Due: ${new Date(record.dueAt).toLocaleString('en-IN')}` : ''].filter(Boolean).join(' · ') || 'No additional details'}</Typography></Box><Stack direction="row" spacing={1} alignItems="center">{record.amountInPaise ? <Typography variant="body2" fontWeight={800}>{money(record.amountInPaise)}</Typography> : null}{record.balanceInPaise ? <Chip size="small" label={`${money(record.balanceInPaise)} due`} /> : null}{nextKind && !TERMINAL.has(record.status) ? <Button size="small" endIcon={<ArrowForwardRoundedIcon />} onClick={() => convert(record, nextKind)} disabled={saving}>To {NEXT_LABEL[nextKind]}</Button> : null}{FINAL_STATUS[record.kind] && !TERMINAL.has(record.status) ? <Button size="small" startIcon={<CheckCircleRoundedIcon />} onClick={() => finish(record)} disabled={saving}>Done</Button> : null}</Stack></Stack>; })}</Stack> : <Typography variant="body2" color="text.secondary" sx={{ py: 4, textAlign: 'center' }}>No {String(LABELS[tab] || tab).toLowerCase()} yet.</Typography>}</CardContent></Card></Stack>;
}
