'use client';
import {useEffect,useMemo,useState} from 'react';
import {useParams} from 'next/navigation';
import {Alert,Badge,Box,Button,Card,CardContent,CardMedia,Chip,Container,Dialog,DialogActions,DialogContent,DialogTitle,IconButton,MenuItem,Paper,Stack,TextField,Typography} from '@mui/material';
import ShoppingBagRoundedIcon from '@mui/icons-material/ShoppingBagRounded';import AddShoppingCartRoundedIcon from '@mui/icons-material/AddShoppingCartRounded';import RemoveRoundedIcon from '@mui/icons-material/RemoveRounded';import AddRoundedIcon from '@mui/icons-material/AddRounded';
const fmt=(v,c)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:c||'INR',maximumFractionDigits:2}).format(Number(v||0)/100);
export default function PublicStore(){
 const params=useParams(),slug=Array.isArray(params?.slug)?params.slug[0]:params?.slug;
 const[store,setStore]=useState(null),[error,setError]=useState(''),[filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[cart,setCart]=useState([]),[open,setOpen]=useState(false),[form,setForm]=useState({customerName:'',phone:'',email:'',notes:''}),[sent,setSent]=useState(null),[saving,setSaving]=useState(false);
 useEffect(()=>{if(slug)fetch(`/api/store/public/${slug}`).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.message);setStore(j.data)}).catch(e=>setError(e.message||'Store unavailable'))},[slug]);
 const products=useMemo(()=>store?.products?.filter(p=>(filter==='all'||String(p.categoryId||'')===filter)&&`${p.name} ${p.shortDescription}`.toLowerCase().includes(search.toLowerCase()))||[],[store,filter,search]);
 const quantity=cart.reduce((s,x)=>s+x.quantity,0),total=cart.reduce((s,x)=>s+(x.salePriceInPaise??x.priceInPaise)*x.quantity,0);
 const add=p=>{setCart(c=>{const found=c.find(x=>x._id===p._id);return found?c.map(x=>x._id===p._id?{...x,quantity:x.quantity+1}:x):[...c,{...p,quantity:p.minOrderQuantity||1}]});setOpen(true)};
 const adjust=(id,d)=>setCart(c=>c.map(x=>x._id===id?{...x,quantity:Math.max(x.minOrderQuantity||1,x.quantity+d)}:x));
 const submit=async()=>{setSaving(true);setError('');try{const r=await fetch(`/api/store/public/${slug}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,items:cart.map(x=>({productId:x._id,quantity:x.quantity}))})});const j=await r.json();if(!r.ok)throw new Error(j.message);setSent(j.data);setCart([])}catch(e){setError(e.message||'Could not send enquiry')}finally{setSaving(false)}};
 if(error&&!store)return <Container maxWidth="sm" sx={{py:10}}><Alert severity="error">{error}</Alert></Container>;if(!store)return <Box sx={{py:12,textAlign:'center'}}><Typography>Loading store…</Typography></Box>;
 const{profile}=store,accent=profile.accentColor||'#5b4bdb';
 return <Box sx={{minHeight:'100vh',bgcolor:'#f7f7fb'}}><Box sx={{bgcolor:'white',borderBottom:'1px solid #e8e8ef',position:'sticky',top:0,zIndex:5}}><Container maxWidth="lg"><Stack direction="row" alignItems="center" spacing={1.5} sx={{height:72}}>{profile.logoUrl&&<Box component="img" src={profile.logoUrl} alt="" sx={{width:42,height:42,objectFit:'contain',borderRadius:1}}/>}<Typography variant="h6" fontWeight={900} flex={1}>{profile.name}</Typography><IconButton onClick={()=>setOpen(true)} aria-label="Open enquiry bag"><Badge badgeContent={quantity} color="error"><ShoppingBagRoundedIcon/></Badge></IconButton></Stack></Container></Box>
 <Box sx={{color:'white',background:profile.heroImageUrl?`linear-gradient(90deg, rgba(15,15,25,.82),rgba(15,15,25,.35)),url(${profile.heroImageUrl}) center/cover`:`linear-gradient(135deg,${accent},#22233a)`,py:{xs:7,md:11}}}><Container maxWidth="lg"><Typography variant="h2" fontWeight={950} sx={{fontSize:{xs:'2.3rem',md:'4rem'},maxWidth:760}}>{profile.tagline||`Welcome to ${profile.name}`}</Typography>{profile.description&&<Typography sx={{mt:2,maxWidth:650,fontSize:{xs:'1rem',md:'1.2rem'},opacity:.9}}>{profile.description}</Typography>}</Container></Box>
 <Container maxWidth="lg" sx={{py:{xs:4,md:7}}}><Stack direction={{xs:'column',md:'row'}} spacing={2} sx={{mb:4}}><TextField fullWidth placeholder="Search products" value={search} onChange={e=>setSearch(e.target.value)}/><TextField select value={filter} onChange={e=>setFilter(e.target.value)} sx={{minWidth:220}}><MenuItem value="all">All categories</MenuItem>{store.categories.map(c=><MenuItem key={c._id} value={c._id}>{c.name}</MenuItem>)}</TextField></Stack>
 {!products.length?<Paper sx={{p:5,textAlign:'center'}}><Typography color="text.secondary">No products match your search.</Typography></Paper>:<Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'repeat(2,1fr)',lg:'repeat(3,1fr)'},gap:3}}>{products.map(p=><Card key={p._id} sx={{borderRadius:4,boxShadow:'0 10px 35px rgba(20,20,45,.08)',display:'flex',flexDirection:'column'}}>{p.images?.[0]?<CardMedia component="img" image={p.images[0]} alt={p.name} sx={{height:260,objectFit:'cover'}}/>:<Box sx={{height:220,display:'grid',placeItems:'center',bgcolor:'#ececf5'}}><ShoppingBagRoundedIcon sx={{fontSize:64,color:'#b1b1c5'}}/></Box>}<CardContent sx={{display:'flex',flexDirection:'column',flex:1}}>{p.isFeatured&&<Chip size="small" label="Featured" sx={{alignSelf:'flex-start',mb:1,bgcolor:`${accent}18`,color:accent}}/>}<Typography variant="h6" fontWeight={800}>{p.name}</Typography><Typography color="text.secondary" variant="body2" sx={{my:1,flex:1}}>{p.shortDescription}</Typography><Stack direction="row" alignItems="center" justifyContent="space-between" spacing={2}><Box><Typography fontWeight={850} color={accent}>{fmt(p.salePriceInPaise??p.priceInPaise,profile.currency)}</Typography>{p.salePriceInPaise!=null&&<Typography variant="caption" sx={{textDecoration:'line-through'}}>{fmt(p.priceInPaise,profile.currency)}</Typography>}</Box><Button variant="contained" onClick={()=>add(p)} startIcon={<AddShoppingCartRoundedIcon/>} sx={{bgcolor:accent,'&:hover':{bgcolor:accent}}}>Enquire</Button></Stack></CardContent></Card>)}</Box>}
 <Stack sx={{mt:7,py:4,borderTop:'1px solid #ddd'}} spacing={.5}><Typography fontWeight={800}>{profile.name}</Typography>{profile.address&&<Typography color="text.secondary">{profile.address}</Typography>}<Typography color="text.secondary">{[profile.phone,profile.email].filter(Boolean).join(' · ')}</Typography></Stack></Container>
 <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Your enquiry</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}>{sent?<><Alert severity="success">Enquiry {sent.inquiryNumber} was sent successfully.</Alert>{sent.whatsapp&&<Button variant="contained" component="a" target="_blank" href={`https://wa.me/${sent.whatsapp}?text=${encodeURIComponent(`Hello, I just sent enquiry ${sent.inquiryNumber}.`)}`}>Continue on WhatsApp</Button>}</>:<>{!cart.length?<Typography color="text.secondary">Your enquiry bag is empty.</Typography>:cart.map(x=><Stack key={x._id} direction="row" alignItems="center" spacing={1}><Box flex={1}><Typography fontWeight={700}>{x.name}</Typography><Typography variant="body2">{fmt(x.salePriceInPaise??x.priceInPaise,profile.currency)}</Typography></Box><IconButton onClick={()=>adjust(x._id,-1)}><RemoveRoundedIcon/></IconButton><Typography>{x.quantity}</Typography><IconButton onClick={()=>adjust(x._id,1)}><AddRoundedIcon/></IconButton></Stack>)}{cart.length>0&&<><Typography variant="h6" fontWeight={850}>Estimated total: {fmt(total,profile.currency)}</Typography><TextField label="Your name" required value={form.customerName} onChange={e=>setForm({...form,customerName:e.target.value})}/><TextField label="Phone / WhatsApp" required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><TextField label="Email (optional)" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><TextField label="Notes (optional)" multiline minRows={2} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/>{error&&<Alert severity="error">{error}</Alert>}</>}</>}</Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Close</Button>{!sent&&cart.length>0&&<Button variant="contained" onClick={submit} disabled={saving||!form.customerName.trim()||form.phone.replace(/\D/g,'').length<7}>{saving?'Sending…':'Send enquiry'}</Button>}</DialogActions></Dialog></Box>;
}
